currentcontext: eu-demo
contexts:
- auth: UmljaGFyZC5OZWF2ZUBpcHNvZnQuY29tOkFudGl0aDIkMiR2dDU2NDIxMjM0NQ==
  domain: eu1.demo.1desk.ai
  name: eu-demo
- auth: YWRtaW46QXV0b21hdGVOMFc=
  domain: stg.1desk.ai
  name: stg
